# Generated by Django 4.1 on 2022-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubPageDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField()),
            ],
        ),
    ]
