# Generated by Django 4.1 on 2022-10-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0003_hubpagedatamodel_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('room_id', models.CharField(max_length=255)),
            ],
        ),
    ]
