# Generated by Django 4.1 on 2022-10-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0004_chatmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubpagedatamodel',
            name='text',
        ),
        migrations.AlterField(
            model_name='hubpagedatamodel',
            name='date',
            field=models.DateTimeField(max_length=255, verbose_name=['%Y-%m-%dT%H:%M']),
        ),
        migrations.AlterField(
            model_name='hubpagedatamodel',
            name='date_end',
            field=models.DateTimeField(default='empty', max_length=255, verbose_name=['%Y-%m-%dT%H:%M']),
        ),
    ]
