# Generated by Django 4.1 on 2022-10-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0005_remove_hubpagedatamodel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubpagedatamodel',
            name='date',
            field=models.DateTimeField(max_length=255, verbose_name=['%Y-%m-%d %H:%M']),
        ),
        migrations.AlterField(
            model_name='hubpagedatamodel',
            name='date_end',
            field=models.DateTimeField(default='empty', max_length=255, verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
