# Generated by Django 4.1 on 2022-10-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0006_alter_hubpagedatamodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='hubpagedatamodel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='StudentHub.hubpagedatamodel'),
        ),
    ]
