# Generated by Django 4.1 on 2022-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHub', '0007_chatmessages_hubpagedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubpagedatamodel',
            name='date_end',
            field=models.DateTimeField(default='2000-01-01 10:10', max_length=255, verbose_name=['%Y-%m-%d %H:%M']),
        ),
    ]
